version: 2

jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:12-browsers

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install && sudo npm install --no-progress -g yo

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Link app
          command: sudo npm link

      # simple test
      - run:
          name: Test - Simple Project Creation
          command: yo ui5g --template empty
      - run:
          name: Test - Simple Project Build
          command: cd project && npm run build && npm run test
      - run:
          name: Clean temp files
          command: rm -rf project

      # typescript test
      - run:
          name: Test - Typescript Project Creation
          command: yo ui5g --template wt-ts
      - run:
          name: Test - Typescript Project Build
          command: cd project && npm run build && npm run test
      - run:
          name: Clean temp files
          command: rm -rf project

      # electron test
      - run:
          name: Test - Electron Project Creation
          command: yo ui5g --template empty --electron
      - run:
          name: Test - Electron Project Build
          command: cd project && npm run build && npm run pack
      - run:
          name: Clean temp files
          command: rm -rf project

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
